challenges:
  lava-challenge:
    active: false
    lava-spawn-height: 10
  random-mob-challenge:
    active: false
    min-delay: 60
    max-delay: 120
  random-effect-challenge:
    active: false
    min-delay: 120
    max-delay: 180
    min-level: 0
    max-level: 9
    infinite-effect-duration: false
    effect-duration: 180
  health-challenge:
    active: false
    health: 6
timer:
  stop-timer-on-death: true
  time: 0
  save-time-between-sessions: false